### ISSUE TITLE
Translation of numbers (in forced translation)

### ISSUE THREAD

**Issue by IdiosApps** [akhilkedia/AllTrans#1]
A text-input field has e.g. my phone number usually, and forced translation with AllTrans actually turns the numbers into words (so my phone number is like thirteen billion fifty two million.....).

Whilst it's quite amusing, it'd be great if there could be an option to omit numbers from translation (should they need translating, anyway?). Turning numbers into words means that the text-input breaks, so I have to disable AllTrans for that app and clear the cache to remember & input my number.

**Comment by akhilkedia** [comment]
I could add a special case for Roman Numerals `(0-9)`, but other languages may have numbers in other forms.
This is an issue not just with numbers, but also other kinds of text in edit boxes.
Perhaps a toggle to "turn off translation in all boxes in which you can input text" is a better approach?

**Comment by IdiosApps** [comment]
Good suggestion at the end of your comment!

Having a toggle for not translating roman numerals would be handy too, as screen space is limited.

For other number systems, such as in (simplified)  Chinese, I don't think you'd want to avoid translating the numbers (一，二，三，...) as they can be contained in words made of multiple characters. This could really confuse the machine translation!

**Comment by joserebelo** [comment]
I think that a toggle for not translating roman numerals would be great. "71" being translated to "Seventy one" when it should fit in a tiny space doesn't really work properly.

**Comment by da3dsoul** [comment]
+1 to not translate Arabic numerals. Roman numerals are I II..X

**Comment by akhilkedia** [comment]
Latest update pushed to github solves this issue - user editable input fields are no longer translated. Will push update xposed repo version soon.
