### ISSUE TITLE
Android Q compatibility

### ISSUE THREAD

**Issue by nofreelogin** [akhilkedia/AllTrans#12]
Hi, I'm desperate to make the app work. I have Android Q and EdXposed installed (sandhook). I followed the instructions but the app doesn't translate. I have valid azure key (although I had to select different region than global as it was allowing to create the form when selecting it). Please, could you let me know what settings/EdXposed version you have been running during the tests?

**Comment by akhilkedia** [comment]
I have released an update that should fix issues with Android Q.
Please download it and test.
If it still does not work, enable "Advanced: Turn on Debug Mode" in AllTrans Global Settings, and post the information mentioned here https://github.com/akhilkedia/AllTrans#if-you-still-have-problems-like-force-close-or-parts-of-an-app-not-being-translated .

**Comment by nofreelogin** [comment]
Thank you. It doesn't work for me. I think it's because the azure key is
set up for Western Europe rather than Global region as per
your instructions. I can't get it validated for global region though:(

**Comment by akhilkedia** [comment]
I recommend you give me the debug log I mentioned above, or personally message me the API key.

**Comment by akhilkedia** [comment]
I checked and can confirm that the region is indeed the issue. For non-global resource, I need to include the region in header for the translation request. I guess I will have to update the app with the region selector.
In the meantime, I recommend somehow making a global key, by perhaps using a free VPN service to change your location.

**Comment by nofreelogin** [comment]
Thanks for your support. I really appreciate this! I tried with 3 different
VPNs without success. I guess I need to wait for your kind app update:)

**Comment by nofreelogin** [comment]
Found o workaround! App is a jam!!:) If someone has the issue with region
he/she should go to resource group on Azure portal first and create new one
with region i.e Norway East (worked for me). Then follow your instructions
but selecting previously resourcing group from drop down menu and global
region! Validation successful!

Thanks:)

**Comment by akhilkedia** [comment]
Updated instructions in the Readme for resource region, closing.
