### ISSUE TITLE
Chinese traditional

### ISSUE THREAD

**Issue by pochen448** [akhilkedia/AllTrans#13]
Can you add Chinese traditional to the settings “Translate to Language” ? please

**Comment by akhilkedia** [comment]
Chinese Traditional is not supported by Google for offline translate, and is therefore not available.
Please use Azure translate for Chinese Traditional.

**Comment by null-von-sushi** [comment]
@akhilkedia would it be possible to reopen this issue? It seems offline translation for traditional is supported now.
![Screenshot_20210808-025050](https://user-images.githubusercontent.com/13616397/128618216-2a35e55b-5e24-4f1d-9305-0df7ccd237ad.jpg)

**Comment by akhilkedia** [comment]
@null-von-sushi The google translate application's translate is different from the google translate mlkit library, which is what this app uses. It still does not support Chinese Traditional, so there until google updates their library to add support for the same, there is nothing I can do.
You can see the list of supported languages here - https://developers.google.com/ml-kit/language/translation/translation-language-support

I raised a request with google to add support for Chinese Traditional, and there has been no update for the last year. 
https://issuetracker.google.com/issues/170592782

To Clarify - Chinese Traditional apps will still be translated to other languages (for example - A Chinese app to English), but if you want to translate other round (English app to Chinese), the output will always be Chinese Simplified.

**Comment by akhilkedia** [comment]
@null-von-sushi Furthermore, the Microsoft Translation Provider option does support Chinese Traditional. You should setup your own Azure API key and use Microsoft instead of google if you need Chinese Traditional support. Note that you will need a credit card (it will not be charged anything) to signup for Azure Translation Key.

The steps for getting the API key are a bit out of date, feel free to open another issue if you are unable to follow the steps listed in the README.

**Comment by null-von-sushi** [comment]
Thanks for providing the source of the list of supported languages, and raising the issue with Google. 

As for the MS thing, I might look into it but I'm not gonna lie it looks a bit scary. Also, not sure how I feel about having any and all translations logged to a real-name verified Microsoft account...
