### ISSUE TITLE
a limitation of translator

### ISSUE THREAD

**Issue by gumpsimon** [akhilkedia/AllTrans#19]
![Screenshot_WeChat_20210107-194634](https://user-images.githubusercontent.com/47892240/103889282-c7675600-50ab-11eb-84ec-33366c96f4eb.png)
I cant translate the message of wechat. but the other txt in wechat can be translated.l really hope you can solve this technology problem.l will donate you for your help.thank you for reading.

**Comment by gumpsimon** [comment]
![Uploading Screenshot_WeChat_20210107-194634.png…]()

**Comment by akhilkedia** [comment]
I can confirm this bug. I will look into it.

**Comment by akhilkedia** [comment]
Unfortunately wechat seems to detect modifications like xposed and then bans the account. I cannot test further on Wechat, so unfortunately translations on wechat shall remain as they are.
