### ISSUE TITLE
Need Help Regarding Sharepreference

### ISSUE THREAD

**Issue by Android1500** [akhilkedia/AllTrans#24]
Actually i m making a module which have its data on preference.xml but as we knw we cant read sharepreference in above sdk 23 so any soloution for this i really appericate if you coul help me

**Comment by akhilkedia** [comment]
Hello.

I use a ContentProvider to get around this issue.

The hooked app asks for the preferences from the AllTrans app using a standard Android Content Resolver at https://github.com/akhilkedia/AllTrans/blob/4b40b6827a335dc3c51809a688736f4d07d09c3d/app/src/main/java/akhil/alltrans/AttachBaseContextHookHandler.java#L70

The AllTrans app has a Content Provider at https://github.com/akhilkedia/AllTrans/blob/master/app/src/main/java/akhil/alltrans/sharedPrefProvider.java

I saw this code in some other modules, and used the same.

**Comment by Android1500** [comment]
> Hello.
> 
> 
> 
> I use a ContentProvider to get around this issue.
> 
> 
> 
> The hooked app asks for the preferences from the AllTrans app using a standard Android Content Resolver at https://github.com/akhilkedia/AllTrans/blob/4b40b6827a335dc3c51809a688736f4d07d09c3d/app/src/main/java/akhil/alltrans/AttachBaseContextHookHandler.java#L70
> 
> 
> 
> The AllTrans app has a Content Provider at https://github.com/akhilkedia/AllTrans/blob/master/app/src/main/java/akhil/alltrans/sharedPrefProvider.java
> 
> 
> 
> I saw this code in some other modules, and used the same.

Thanks for your fix but i solved it by just change target api 23 pretty simple
