### ISSUE TITLE
Not all apps are shown ?

### ISSUE THREAD

**Issue by tineprogramming** [akhilkedia/AllTrans#43]
I have so many apps on my samsung note10+ phone but only 4 apps are shown ?
![Screenshot_20220515-232044_AllTrans](https://user-images.githubusercontent.com/18547587/168477622-43ec68b8-6055-4cf7-8dd7-7a8a23646869.jpg)

**Comment by akhilkedia** [comment]
You are probably using a non-root xposed like TaiChi or virtual posed or similar. Only the apps inside these sandbox (TaiChi or vietualxposed or others) are shown.

Please install any app you need to translate inside the sandbox, and they will all show up.

I'm case you have xposed working globally (such as with magisk), please uninstall TaiChi or virtualxposed.

**Comment by tineprogramming** [comment]
I have LPosed installed but used virtual xposed before. What do I need to do ?
![Screenshot_20220516-020430_Shell](https://user-images.githubusercontent.com/18547587/168485005-01249232-747b-465a-85bc-fdd2a95f5abb.jpg)

**Comment by akhilkedia** [comment]
Simply uninstall the virtualxposed app, and all the others apps will show up in alltrans.

**Comment by tineprogramming** [comment]
Thank you so much
