### ISSUE TITLE
Alternative 

### ISSUE THREAD

**Issue by jason-stream** [akhilkedia/AllTrans#58]
What's the current alternative since AllTrans' development is dead?

**Comment by zinhuofc** [comment]
unfortunately there is no alternative, so we need to look for a new developer who wants to take on this project
I'm always posting in groups to see if anyone can find it, this is a good project that can't be killed :/

**Comment by akhilkedia** [comment]
AllTrans for me was always something I built just for my personal use.
For the first 3 years, I used this without even a GUI, just compiling it whenever I needed to change anything.

I decided to release the app as I thought it might help others.
As long as I use it personally, I will keep AllTrans running (atleast on whichever version of Android I happen to be using.)

Unfortunately, I do not have the time to dedicate to extra features, port to other android versions/other manufacturer's variation, etc.

If there is another developer here who is willing to take up the work of maintaining alltrans, I can explain the architecture etc. of the code. Or feel free to send pull requests.

Taking Alltrans towards a paid/fremium model may give me enough incentive to work on it. Not sure if that is a direction I want to take - as AllTrans is currently fully free and open-source.

**Comment by zinhuofc** [comment]
> AllTrans for me was always something I built just for my personal use. For the first 3 years, I used this without even a GUI, just compiling it whenever I needed to change anything.
> 
> I decided to release the app as I thought it might help others. As long as I use it personally, I will keep AllTrans running (atleast on whichever version of Android I happen to be using.)
> 
> Unfortunately, I do not have the time to dedicate to extra features, port to other android versions/other manufacturer's variation, etc.
> 
> If there is another developer here who is willing to take up the work of maintaining alltrans, I can explain the architecture etc. of the code. Or feel free to send pull requests.
> 
> Taking Alltrans towards a paid/fremium model may give me enough incentive to work on it. Not sure if that is a direction I want to take - as AllTrans is currently fully free and open-source.

man you don't know how happy i am to see your update :D i love you. you can be sure that you help many people because your work is unique, your application makes me connect with many people from other countries that I don't know the language, it would be great if other devs support you, I looked for many while you didn't give news anymore I did not succeed
If your decision to take paid/fremium is good for you and your development I'm sure many will support you

**Comment by zinhuofc** [comment]
the translation with google did not work in any app, I still need to test it with azure

**Comment by akhilkedia** [comment]
See the instructions in the Readme, and submit a log. Could you open a
separate issue for this so it can be better tracked there?
The release version on github works for me with google's offline translate,
I just checked. ¯\_(ツ)_/¯

**Comment by zinhuofc** [comment]
> 

yes i will do it now

**Comment by fr-jason-fr** [comment]
Does this work on CoolApk?
