### ISSUE TITLE
Android Q support? 

### ISSUE THREAD

**Issue by usamaiqbal1177** [akhilkedia/AllTrans#8]
This is an awesome super useful module. Please continue its development for Android Q. It doesn't work on Q right now

**Comment by akhilkedia** [comment]
I have received multiple reports of people successfully using this with Edxposed on Android Q. Do other xposed modules work for you?
I unfortunately don't have an Android Q device yet to test AllTrans. I will look into emulators and update the app if required.

**Comment by akhilkedia** [comment]
Some people have told me Edxposed Beta works better with AllTrans - can you try with the latest Edxposed beta and see if you still have issues with AllTrans?

**Comment by usamaiqbal1177** [comment]
> Some people have told me Edxposed Beta works better with AllTrans - can you try with the latest Edxposed beta and see if you still have issues with AllTrans?

I use canary builds. Only they work fine on android 10. Most of the modules work fine on android 10... I'll test it again with my canary edxposed. Please tell me what type of log should I provide you to assist with the app.. I'm more than willing to help AllTrans in every way possible. 🤗

**Comment by akhilkedia** [comment]
First, go in `Global Settings` and turn on `Advanced: Turn on Debug Mode`.
Then, I will need atleast the following information - 

1. The name of the app you are trying to translate, along with a **link to download the app** from some APK store like `Google Play Store`, `CoolApk`, etc.

2. A `"logcat"` of you trying to open the app which gives you problems.
You can use apps freely available on the Play Store for this, such as [This one](https://play.google.com/store/apps/details?id=com.nolanlawson.logcat). 
 Force close the app you are trying to translate, and then just open the app you are trying to translate. After this, send me the logcat file.

**Comment by akhilkedia** [comment]
Personally verified that the latest version works on Android Q without any issues.

**Comment by nofreelogin** [comment]
Hi, I'm desperate to make the app work. I have Android Q and EdXposed installed. I followed the instructions but the app doesn't translate. Please, could you let me know what settings/EdXposed version you have been running during the tests?
